### ISSUE TITLE
[ROADMAP] Initial relase

### ISSUE THREAD

**Issue by tqchen** [tlc-pack/tlcpack#1]
- [ ] script to build cpu binary wheel, tlcpack-dev.whl
    - Consider use tvm docker infra to setup the build env
- [ ] script to build cuda binary, tlcpack-cu10-dev.whl
    - Consider use docker to setup the build env
- [ ] decide name for dev(unstable release) perhaps dev suffix?
